### ISSUE TITLE
Mocks(?) won't generate on `mocks-dir` but on `root-dir`

### ISSUE THREAD

**Issue by shackra** [subtle-byte/mockigo#14]
I'm working on my project, on this branch https://gitlab.com/shackra/goimapnotify/-/tree/35-make-key-structs-more-testable?ref_type=heads

I noticed that running `mockigo` (I'm running `latest` version) generates a file on the root of the project, this is my configuration:

```yaml
root-dir: .
mocks-dir: ./mocks
walk:
  - "!."
  - "idleClient"
```

the file generated is called `mocks_test.go`, but I was expecting to be generated on `mocks/` as indicated in the configuration. What is going on?
